<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Taille extends \App\Entity\Taille implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'complement', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'menuTailles', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'boissonTailles'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'complement', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'menuTailles', '' . "\0" . 'App\\Entity\\Taille' . "\0" . 'boissonTailles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Taille $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle(string $libelle): \App\Entity\Taille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\Taille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplement(): ?\App\Entity\Complements
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplement', []);

        return parent::getComplement();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplement(?\App\Entity\Complements $complement): \App\Entity\Taille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplement', [$complement]);

        return parent::setComplement($complement);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuTailles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuTailles', []);

        return parent::getMenuTailles();
    }

    /**
     * {@inheritDoc}
     */
    public function addMenuTaille(\App\Entity\MenuTaille $menuTaille): \App\Entity\Taille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMenuTaille', [$menuTaille]);

        return parent::addMenuTaille($menuTaille);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMenuTaille(\App\Entity\MenuTaille $menuTaille): \App\Entity\Taille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMenuTaille', [$menuTaille]);

        return parent::removeMenuTaille($menuTaille);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoissonTailles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoissonTailles', []);

        return parent::getBoissonTailles();
    }

    /**
     * {@inheritDoc}
     */
    public function addBoissonTaille(\App\Entity\BoissonTaille $boissonTaille): \App\Entity\Taille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBoissonTaille', [$boissonTaille]);

        return parent::addBoissonTaille($boissonTaille);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBoissonTaille(\App\Entity\BoissonTaille $boissonTaille): \App\Entity\Taille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBoissonTaille', [$boissonTaille]);

        return parent::removeBoissonTaille($boissonTaille);
    }

}
