<?php

namespace ContainerW2qx1V8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatalogueDataproviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataProvider\CatalogueDataprovider' shared autowired service.
     *
     * @return \App\DataProvider\CatalogueDataprovider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataProvider/CatalogueDataprovider.php';

        return $container->privates['App\\DataProvider\\CatalogueDataprovider'] = new \App\DataProvider\CatalogueDataprovider(($container->privates['App\\Repository\\BurgerRepository'] ?? $container->load('getBurgerRepositoryService')), ($container->privates['App\\Repository\\MenuRepository'] ?? $container->load('getMenuRepositoryService')));
    }
}
