<?php

namespace ContainerJBEP6xy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeDataPersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\CommandeDataPersister' shared autowired service.
     *
     * @return \App\DataPersister\CommandeDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataPersister/CommandeDataPersister.php';
        include_once \dirname(__DIR__, 4).'/src/Service/NumeroCommande.php';

        return $container->privates['App\\DataPersister\\CommandeDataPersister'] = new \App\DataPersister\CommandeDataPersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), new \App\Service\NumeroCommande());
    }
}
