<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJBEP6xy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJBEP6xy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJBEP6xy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJBEP6xy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJBEP6xy\App_KernelDevDebugContainer([
    'container.build_hash' => 'JBEP6xy',
    'container.build_id' => 'b50f4fec',
    'container.build_time' => 1658854869,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJBEP6xy');
